#!/bin/bash

# This script is used to generate environment and other settings needed by the e2e tests.
#
# It should be ran BEFORE running the e2e tests.
# Usage:
#   ./generate-e2e-config.sh testnet|preview|local

e2e_env_file=".env.e2e"

echo -e "### Below settings have been auto-generated by generate_env_info.sh ###\n" > $e2e_env_file

# environment to run against
port=${PORT:-3000}
case $1 in
  testnet)
    base_url="https://app.testnet.onbeam.com"
    ;;
  preview)
    base_url="https://app.preview.onbeam.com"
    ;;
  local)
    base_url="http://localhost:$port"
    ;;
  *)
    echo "Wrong argument! Please provide one of: testnet|preview|local."
    exit 1
    ;;
esac

echo "BASE_URL=$base_url" >> $e2e_env_file

# secrets for the e2e tests
echo "VERCEL_PASSWORD=$(aws secretsmanager get-secret-value --secret-id e2e-vercel-login-password-2 --query SecretString \
  --output text)" >> $e2e_env_file
aws secretsmanager get-secret-value \
  --secret-id e2e-google-api-oauth2-credentials \
  --query SecretString \
  --output text > secrets/e2e-google-api-oauth2-credentials.json
aws secretsmanager get-secret-value \
  --secret-id e2e-gmail-api-access-token \
  --query SecretString \
  --output text > secrets/e2e-gmail-api-access-token.json

# Paths need to be relative against the .env filepath as defined in $e2e_env_file
echo "GOOGLE_API_OAUTH2_CREDENTIALS_PATH=secrets/e2e-google-api-oauth2-credentials.json" >> $e2e_env_file
echo "GMAIL_API_ACCESS_TOKEN_PATH=secrets/e2e-gmail-api-access-token.json" >> $e2e_env_file

echo -e "\n### End of auto-generated settings ###" >> $e2e_env_file
