name: Testnet E2E validation

on:
  workflow_dispatch: # Allow running the workflow manually from the GitHub UI

  schedule:
    - cron: '0 0 * * *' # every day at 00:00 UTC

env:
  AWS_REGION: eu-central-1
  HTML_REPORTS_BUCKET: beam-e2e-test-reports

jobs:
  run-e2e-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    name: "Run E2E tests"

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: 📥 dependency installation
      uses: ./.github/actions/pnpm-install

    - name: Retrieve playwright version
      id: playwright-version
      run: echo "PLAYWRIGHT_VERSION=$(pnpm info @playwright/test version)" >> $GITHUB_ENV

    - name: Cache playwright
      uses: actions/cache@v3
      id: playwright-cache
      with:
        path: |
          ~/.cache/ms-playwright
        key: ${{ runner.os }}-playwright-${{ env.PLAYWRIGHT_VERSION }}

    - name: Install Playwright Browsers
      run: pnpm playwright install --with-deps chromium
      if: steps.playwright-cache.outputs.cache-hit != 'true'

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ vars.PLAYWRIGHT_AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.PLAYWRIGHT_AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Generate E2E config
      run: ./generate-e2e-config.sh testnet

    - name: Run Playwright tests
      run: pnpm playwright test

    - name: Upload Playwright HTML report to S3
      if: always()
      run: |
        date=$(date '+%Y-%m-%d-%H-%M-%S')

        ./upload-e2e-test-report.sh ${{ env.HTML_REPORTS_BUCKET }} $date

        html_report_url="https://e2e.onbeam.com/$date/index.html"

        echo "### 🎭 [Playwright HTML Report]($html_report_url)" >> $GITHUB_STEP_SUMMARY